rbspy/rbspy

- Cargo.toml
- src/bin/ruby-stacktrace.rs
- src/lib.rs
- src/test_utils.rs
Hey! I wanted to use your process-memory-reading code for another project, so I split it out to a standalone crate:
https://github.com/luser/read-process-memory
https://crates.io/crates/read-process-memory
Here's a PR to remove that code from this project and make it use that crate instead. I even added a Windows implementation to that crate if you ever get strangely motivated to make ruby-stacktrace work on Windows. :)
While I was removing code I removed all but one of your `unsafe` blocks! I think some of them were probably just leftovers from previous hacking.
> Use the new read-process-memory crate

- README.md
I was wondering whether this tool will capture all threads of a ruby process.
Seems yes: I wrote [simple code][1] with different functions eating cpu in 2 sub-threads, run ruby-stacktrace on both main PID and thread PIDs, and got same picture from all of them, showing both cpu-eating functions:
```
self | tot  | method
42.0% | 100.0% | work : /home/bpaskinc/work-in-subthread.rb
30.0% | 13.5% | dumb_work : /home/bpaskinc/work-in-subthread.rb
28.0% | 6.5% | block in dumb_work : /home/bpaskinc/work-in-subthread.rb
```
However I wonder about the numbers.
`work` shows as total 100% but it was only one thread.
`dumb_work` doesn't add up to nearly another 100%.  (I suspect because `Range#each` is written C?)
OK, so what if I add another `work` thread?
```
self | tot  | method
60.0% | 100.0% | …
```
> Mentions threads in README

- .gitignore
- examples/short_program.rb
- src/bin/ruby-stacktrace.rs
This makes it possible to execute & profile a subprocess. This is important because it lets us profile processes without being root -- if you exec a subprocess, then you can `process_vm_readv` that subprocess even if you're unprivileged.
> Make it possible to profile a subprocess

- build.sh
- docker/Dockerfile.fedora
- docker/Dockerfile.ubuntu1404
- docker/Dockerfile.ubuntu1604
2 improvements to the integration tests:
* fixes a bug where it was always using the ubuntu 14.04 docker image when running the tests instead of using the appropriate distro image
* store all the build artifacts shared with the docker image in /tmp/artifacts instead of in the docker/ directory
> Improvements to integration tests

- src/lib.rs
Preliminary support for profiling system Ruby. This only works for Ruby circa 2.3.1, but it does work on Ubuntu 16.04 in the tests!
The exciting part of this is that it works even if the system Ruby doesn't include debugging symbols!!
The key functions in this PR are `get_thread_address_alt` and `get_api_address` -- `get_thread_address_alt` is a alternative way of finding the address of the global `ruby_current_thread` variable. 
`get_api_address` has been modified to work even if the symbols are missing. It turns out that even if symbols are stripped, the symbol for `ruby_api_version` will still be present in the libruby shared object file. So we just find the right shared object file and look it up.
This is all relatively fragile right now (and definitely only works on Linux) but it's a …
> Support profiling system ruby on Ubuntu 16.04

- Cargo.lock
- Cargo.toml
- src/bin/ruby-stacktrace.rs
The goal is to sample every X milliseconds. Previously this was doing a `time.sleep(10ms)` which doesn't. actually sample every 10ms, instead it samples every 10ms + however long it took to take a CPU sample.
This is a little more accurate! I tested it and it looks like if I sample every 10ms, it takes about 99 samples per second (instead of 100 samples per second). Close!
> Slightly more accurate CPU sampling

- Cargo.lock
- Cargo.toml
- src/bin/ruby-stacktrace.rs
Also logs dropping stack traces instead of stopping the program entirely.
> Add option to pause Ruby process while collecting stack traces

- README.md
- src/main.rs
This allows for adjusting how much load rbspy incurs on the profiled application by adjusting how frequently samples are collected. Additionally, setting for odd frequencies such and `97` can improve the quality of the samples due to sleep intervals or scheduled jobs in the profiled process.
https://github.com/rbspy/rbspy/issues/55
This is my first time working with Rust so I expect I need some stylistic tweaks.
> Add sample rate CLI option for Record subcommand

- ci/script.sh
- src/address_finder.rs
- src/initialize.rs
- src/ruby_version.rs
Previously we looked up the heap's memory map in `/proc/$PID/maps` and used that as a way to sanity check addresses that should be on the heap. It turns out that this doesn't work with jemalloc and tcmalloc, so this PR just removes the code that looks up the heap's memory map and instead just checks that the addresses we're sanity checking are *somewhere* in the process's memory maps.
This also adds two small tests that LD_PRELOAD jemalloc/tcmalloc to make sure that the profiler actually works with those two mallocs.
> Add jemalloc & tcmalloc support

- README.md
- src/main.rs
This  checks the time elapsed on every collected stacktrace to see if we are have hit the users specified duration threshold if they set the duration.
> Record for fixed length of time

- src/main.rs
The filename writes out the raw stacks, and is unable to write the flamegraph if the user specifies a file with the .svg extension.
> Validate user's filename

- src/initialize.rs
- src/ruby_version.rs
This makes the debugging output more organized/useful -- the main time I think debugging output will be useful is when there's an error getting a stack trace. So this moves most of the debug printing to the case where there's actually an error.
This should make it easier to ask users "hey, if you run into an error, rerun it with `env RUST_LOG=debug` and send us the output of that"
This prints out the cfp, iseq, and thread structs, as well as the rstring struct, which I'm hoping will be a good start.
> Only print debug output when there are errors

- Cargo.lock
- Cargo.toml
- src/address_finder.rs
- src/main.rs
Fixes #67.
This adds support for profiling Ruby processes running in Linux containers! 
The only reason rbspy **didn't** work with containers was -- there's a small part at the beginning of the program where it reads 1 or 2 binaries from the program's memory maps (the Ruby binary, and sometimes another dynamically linked library). 
It's also worth making "work with containers" more precise -- the real issue was that the target process was in a **different mount namespace** (/usr/bin/ruby1.9.1 in the target process didn't mean the same thing as /usr/bin/ruby1.9.1 in rbspy's process). 
So to make rbspy work with containerized processes, we just need to switch to the target process's mount namespace before reading those two ELF binaries. Then after reading the ELF binaries we switch back to …
> Add support for profiling processes in Linux containers

- Cargo.lock
- Cargo.toml
- src/address_finder.rs
- src/main.rs
This reverts the previous commit adding container support and implements a much simpler approach instead! 
It turns out that to read a file from a process's mount namespace, you can just read it from `/proc/PID/root/<filename>`. I like this because we can just always implement the same approach whether the target process is running in a container or not!
> Simplify container support

- src/callgrind.rs
- src/initialize.rs
- src/main.rs
- src/output.rs
Flamegraphs are awesome! But sometimes there are better ways to visualize your program.
For example, here's the [dumbest fibonacci calculator ever](https://gist.github.com/vasi/ae3b25ce7bfd7540be6c3970b9a0a4f6), and the flamegraph rbspy generates:
It's super hard to tell what's wrong. Even though `fib0` is being called a gazillion times and doing loads of work, it doesn't really show up. On the other hand, I can run.:
```
sudo ./target/debug/rbspy record -f ../callgrind.out --format callgrind ./fib.rb 19
```
And then open `callgrind.out` with [qcachegrind](https://kcachegrind.github.io/html/Home.html), I get some really useful output:
Clearly "block in fib0" has something wrong!
* qcachegrind can do some nice visualizations:
* callgrind files are much smaller than flamegraphs—easier to …
> Add callgrind output

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- ci/script.sh
- src/address_finder.rs
- src/copy.rs
- src/initialize.rs
- src/mac_maps.rs
- src/main.rs
Preliminary Mac support! In my testing so far, this works with Ruby (as long as it's installed by rbenv) on Mac.
This does **not** work with system Ruby on Mac. There are a couple issues with adding system Ruby support:
1. SIP -- getting a port to talk to system Ruby is impossible if you have SIP enabled on your Mac (tested this today). I believe this isn't fixable, the whole point of SIP is to prevent other programs from instrumenting your program in exactly this way.
2. my implementation of `get_process_maps` right now doesn't support dynamically loaded libraries, and all the symbols in system Ruby (at least on the High Sierra mac I'm working with) are in a dynamically loaded library which I haven't been about to find the address or path of yet. more notes about the difficulties there …
> Mac support

- src/initialize.rs
- src/main.rs
I realized the existing sleep (in `task_for_pid` in mac_maps.rs) isn't enough to prevent the race between task_for_pid and exec'ing a process that causes freezes in High Sierra.
I think these are the only other 2 places that need it right now. I'd rather write this code in a cleaner way but I'm not seeing how to do it right now -- it's annoying because we both start processes and run `task_for_pid` in several places (through both `.try_into_process_handle` and `task_for_pid` directly). Probably worth refactoring later so that there's only one place that PIDs get translated into Mach tasks on Mac, and then we can make sure to always sleep there.
> Add more sleeps to prevent freezing on High Sierra

- src/main.rs
Fixes #88 
rbspy doesn't work unless you're root on Mac. However we should wait to make that check until we're done parsing the command line arguments.
> Don't require root to get the version

- Cargo.lock
- src/copy.rs
- src/ruby_version.rs
Fixes #87 
get_lineno was panicking because of an overflow -- we were sometimes subtracing two usizes `a-b` where `a < b`. I'm pretty sure this is because rbspy is in a race trying to read memory. The way we're handling these errors elsewhere is just to return an error and then possibly retry.
So this adds a check to see if `a < b` and if so returns an error. If `a >= b`, then doing the subtraction is fine.
> Turn overflow panic in get_lineno into error

- README.md
It looks like mac support was added in #69 so I thought maybe this was missed in 5f7b3615. I thought Macs still weren't supported due to this.
> remove "Mac support" from Missing Features list

- Cargo.lock
- Cargo.toml
- src/ruby_version.rs
Previously we were leaving C functions out of the stack that rbspy reports entirely. A most correct way to handle this is to instead report them as "unknown C function" -- this still doesn't give much insight into what the unknown C function **is** exactly but is a big improvement.
This PR both updates the code to report "unknown C function" when it think that's what happening, and adds a test with a core dump from a program which is running a C function. The new core dump would have previously returned an error from `get_stack_trace` and now returns an "unknown C function" stack.
This was causing an issue with profiling Ruby HTTP servers (for instance Sinatra), which sometimes spend a lot of time in the `select` syscall with no other Ruby function running -- rbspy would think 80% of the …
> Report C functions in the Ruby stack as "unknown C function"

- src/main.rs
- src/ui/mod.rs
- src/ui/output.rs
- src/ui/summary.rs
This adds 2 new output formats -- a summary and a summary by line number. The idea here is sometimes you just want to get a quick idea of what your hot spots are and don't want to look at a flamegraph or callgrind output.
**summary format**
```
% self  % total  name
19.86   100.00  <c function> - unknown
15.65    15.65  source_range - /home/bork/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/node.rb
13.04    36.31  block in tokens - /home/bork/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/mixin/surrounding_space.rb
6.02     6.02  end_pos - /home/bork/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/token.rb
4.31    60.68  block (2 levels) in on_send - …
```
> Add new 'summary' and 'summary_line' output formats

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/ui/summary.rs
This makes rbspy always show a summary when profiling, like this:
```
Recording data to /tmp/blah.txt
Summary of profiling data so far:
% self  % total  name
27.80   100.00  <c function> - unknown
7.64    19.35  block in tokens - /home/bork/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/cop/mixin/surrounding_space.rb
7.43     7.49  source_range - /home/bork/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/ast/node.rb
4.22     7.67  advance - /home/bork/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/parser-2.4.0.2/lib/parser/lexer.rb
3.62     3.65  end_pos - /home/bork/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rubocop-0.52.1/lib/rubocop/token.rb
2.88    41.49  block (2 levels) in on_send - …
```
> Always show live summary when recording profiling data

- src/ui/output.rs
This changes the parameters we pass to `flamegraph.pl` -- the idea is that icicle graphs are in general easier to read (because in a big one you don't have to scroll down to the bottom).
Changing to minwidth=2 will also help with file sizes.
> Switch default to icicle graph

- README.md
In my first two reads of the README I managed to miss the spawn process method,
it is possible others are similarly overlooking this great feature.
Please let me know if something should change for this PR to be a good fit!
> Accentuated record by spawning process method in README

- Cargo.toml
- src/main.rs
- src/ui/flamegraph.rs
- src/ui/mod.rs
- src/ui/output.rs
This aggregates stack samples in memory instead of writing them to disk and then making the perl script do the aggregation. motivations:
* reduces writes to disk
* means that the flamegraph output isn't a special snowflake, which means we can have a cleaner `Outputter` trait
I'm most excited about reason 2 right now because I want rbspy to *always* record raw data (not just when it's writing a flamegraph), and this will make it easier to add the "always record raw data" feature.
> Aggregate flamegraph samples while rbspy is running

- Cargo.lock
- Cargo.toml
- README.md
- src/core/initialize.rs
- src/main.rs
- src/storage/mod.rs
- src/storage/v0.rs
This pull request:
a) makes `rbspy record` save raw data to disk (the raw data format here is newline-separated JSON, which is then gzipped). I don't really see any reason to use a fancier format, since gzipping doesn't take that much time and reduces the filesize of the JSON by about 10x. The raw data format is versioned (h/t @kamalmarhubi) so that we can easily maintain backwards compatibility if/when we change the raw data format.
b) adds a new subcommand called `report` which lets you create new visualizations from saved recorded data!
I'm excited about the new `report` subcommand because it means that if you decide after the fact that you want to visualize your data a different way, you can!
would love any code review / comments on the design!
I've updated the README to explain the …
> Add new `rbspy report` subcommand

- Cargo.lock
- Cargo.toml
- src/core/initialize.rs
- src/core/ruby_version.rs
- src/main.rs
- src/storage/mod.rs
- src/storage/v0.rs
- src/storage/v1.rs
- src/ui/output.rs
This updates the data storage format for rbspy to include a PID for each stack trace. The idea here is that sometimes we'll sample stack traces from multiple processes, so it's good to include a PID for each stack trace. This is to support the subprocess profiling work by @liaden.
> Add stack trace struct containing PID

- src/core/initialize.rs
- src/core/mod.rs
- src/core/ruby_version.rs
- src/core/types.rs
- src/storage/mod.rs
- src/storage/v0.rs
- src/storage/v1.rs
- src/ui/callgrind.rs
- src/ui/flamegraph.rs
- src/ui/output.rs
- src/ui/summary.rs
Previously we were including C functions in the summary rbspy prints out. I think it's appropriate to include C functions in a flamegraph, but in the summary they were just causing confusion -- it would report something like "50% of time spend in unknown C function", when in reality those are all probably different C functions.
With this PR, "unknown C function" is only included in the summary if it's the only thing in the stack trace.
> Ignore C functions in summary rbspy prints out

- src/core/address_finder.rs
- src/core/copy.rs
- src/core/initialize.rs
- src/core/ruby_version.rs
cc @parkr
Fixes #111 
At some point we introduced a bug where profiling Ruby processes with no symbols stopped working, because we broke the heuristic for finding the address of the current thread. I'm not sure what broke this exactly, but instead of figuring out what went wrong this just makes the logic a lot more robust.
In addition to looking at various random heuristics, at the end of the `is_maybe_thread` we try to get a stack trace assuming that the address we pass in is the actual address of the current thread, and see if it works. That's kind of the ultimate test so it should be much more reliable :)
Also added a regression test to make sure that the bug doesn't come back.
> Fix bug with profiling system Ruby

- ci/docker-tests.sh
- ci/ruby-programs/ruby_forks.rb
- src/core/initialize.rs
- src/main.rs
- src/ui/descendents.rs
- src/ui/mod.rs
This is #86, but rebased on master and squashed into a single commit. I also removed the glob & procinfo dependencies in favour of just parsing /proc/PID/status manually (since it's like 10 lines of code to parse that file and I'd sorta like to keep dependencies under control).
planning to write maybe marginally better tests then merge it!
> Add --subprocesses flag to rbspy record

- src/main.rs
> Make rbspy report not require root on Mac

- src/core/address_finder.rs
- src/core/copy.rs
Add a more helpful message when permission denied errors arise. See #119 for a little background.
Note: This is a Linux specific error that came up for me under docker. Fix it in docker with `docker run --cap-add SYS_PTRACE`
> Include sys_ptrace capability information in the error

- src/ui/output.rs
- src/ui/summary.rs
Since different instances of 'unknown C function' may refer to totally different functions, it confuses the callgrind output and doesn't really help you figure out what's going on at all.
We leave in "unknown C function" if it's the only function on the stack.
> Filter out 'unknown C function' functions when generating callgrind summary

- src/main.rs
If you ask rbspy to sample at too high of a rate, it'll start spitting out errors like:
```
Behind expected sample time by 25982 nanoseconds, results may be inaccurate. Try sampling at a lower rate with `--rate`. Current rate: 3000.
```
The issue with these errors right now is that it doesn't tell you the *magnitude* of the problem -- if 1 stack trace is late, it's not a big deal, but if 50% of stack traces are late then that means our results could be pretty inaccurate.
This PR changes the reporting to report the *percentage* of stack traces that were collected late. We only print out a percentage if it's more than 0.5%.
> Report "trace late" errors in a more understandable way

- Cargo.lock
- Cargo.toml
- src/main.rs
Fixes https://github.com/rbspy/rbspy/issues/130. This will automatically get the version from the Cargo.toml configuration file.
Also the version in the Cargo.toml file wasn't up to date.
> Make rbspy -V report the version

- src/core/address_finder.rs
- src/core/initialize.rs
Previously we were getting this compile warning on Linux
```
warning: variant is never constructed: `MacPermissionDenied`
--> src/core/address_finder.rs:18:5
|
18 |     MacPermissionDenied(pid_t),
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: #[warn(dead_code)] on by default
```
This fixes it by only including the variant on Mac.
> Fix MacPermissionDenied compile warning

- Cargo.lock
- Cargo.toml
- ci/script.sh
- src/core/mac_maps.rs
- src/main.rs
- src/ui/descendents.rs
Currently --subprocesses flag is not available on darwin platform,
because subprocess retrieving logic is Linux-specific.
This change
* Bumps `libproc` version to "0.3.1", because the new version
introduces `proc_pid::pidinfo` function, useful for retrieving
PPIDs.
* Implements darwin-specific `ui::descendents::descendents_of` based
on the new `libproc` functionality.
* Enables `test_spawn_record_children_subprocesses` test for darwin
and tweaks it not to use system Ruby for reasons described in #69
> [Closes #148] Support --subprocesses flag on Mac

- src/main.rs
- src/ui/descendents.rs
- src/ui/mod.rs
- src/ui/output.rs
- src/ui/speedscope.rs
Hi! This is a PR to generate output from rbspy that can be consumed by https://www.speedscope.app/ for fast interactive flamechart visualization & exploration in-browser.
To test this out, generate a profile, then convert it to a speedscope json file like so:
```
report -i /Users/jlfwong/.cache/rbspy/records/rbspy-2018-07-12-4h5BlXOheu.raw.gz -f speedscope -o ~/Downloads/foo.speedscope.json
```
Then drop the resulting `.speedscope.json` file into https://www.speedscope.app/
This is my first ever PR in Rust, so I expect there to be a lot of changes needed before this can plausibly land.
My eventual plan is to make this integration even more seamless, so you don't even need to find the json file output and drag it into browser. Ideally you'd be able to do something like `rbspy view …
> Include an output format for speedscope

- src/main.rs
Since there are no defaults for the `--input` and `--output` arguments of `rbspy report`, an error was returned when accessing them through `value_t!`, which was then unwrapped:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { message: "\u{1b}[1;31merror:\u{1b}[0m The argument \'output\' wasn\'t found", kind: ArgumentNotFound, info: Some(["output"]) }', libcore/result.rs:945:5
Making them mandatory causes clap to exit when first parsing the arguments, which aligns with how other mandatory arguments are being handled. I tried to add a test for the error handling, but since currently `Args::from` exits the process when it can't parse the arguments it would have taken more refactoring. I think there's a pretty low chance of regression here anyway, so I've just …
> Make the --input and --output arguments to rbspy report mandatory

- Cargo.lock
- Cargo.toml
- src/main.rs
This PR contains a few distinct changes, bundled together because the code they touch overlaps. (I can break things out/back parts out if needed.)
* Remove some unused dependencies
* Don't require the nix package on Windows (all uses are already in `cfg(unix)` blocks)
* More substantively: previously, a warning was printed on MacOS if `rbspy report` was invoked by a non-root user, even though that command doesn't actually require root and works without it. Reorder things so that the test for root is only executed when needed.
* Finally, print the non-root warning to stderr instead of stdout
> Omit MacOS root warning for rbspy report

- src/core/copy.rs
When the profiled process on Windows exits, there is usually a [299 error code returned](https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-#error_partial_copy)
from the read_process_memory call. Treat this like the process exitted.
> Handle process exitting on Windows

- src/main.rs
This PR adds the `sample rate` to the print summary when the current rate is lower than the setting. 
This is in response to: https://github.com/rbspy/rbspy/issues/188
Let me know if the verbiage should be changed, or if there's anything else I've missed. I'm a complete beginner with Rust 😅
> Add current sample rate to print summary

- ruby-structs/src/ruby_2_3_8.rs
- ruby-structs/src/ruby_2_4_5.rs
- ruby-structs/src/ruby_2_5_3.rs
- src/core/initialize.rs
**Note: This is a PR to fix a PR (#195)** 😄 
This fixes the following error on the `support-ruby-versions` branch:
```
thread '<unnamed>' panicked at 'Ruby version not supported yet: 2.5.3. Please create a GitHub issue and we'll fix it!', src/core/initialize.rs:252:14
```
I tested it out locally on 2.5.3 and it worked for me 👍 .
> Add 2.3.8 and 2.5.3 to #is_maybe_thread_function

- Cargo.lock
- Cargo.toml
- src/main.rs
As we discussed in https://github.com/rbspy/rbspy/pull/199, sometimes it is needed to turn off the logging of the profiler's summary data.
P.S Can you please release the latest rpspy version, so we can share a link to it?
> Add --silent flag, which allows to cancel every second logging

- Cargo.lock
The warning is coming from clap's `arg_enum!` macro, which has been
fixed already.
> Upgrade crates to fix #198

- src/ui/flamegraph.rs
Since Rust 1.28.0, unit tests can return Result.
> Fix "warning: unused `std::result::Result` that must be used"

- scripts/bindgen.sh
Still ruby has to be cloned as ~/clones/ruby, but rbspy doesn't have
to cloned as ~/work/rbspy.
> Less hard-coding on scripts/bindgen.sh

- scripts/bindgen.sh
I was able to run `sh ./scripts/bindgen.sh 2_6_2` on my MacBook, then realized that all bindgen-generated files were apparently generated on Linux (my ruby_2_6_2.rs mentions "darwin" here and there...). So, I don't include the .rs file on this pull request.
> Small fixes for scripts/bindgen.sh

- README.md
Hello,
I saw https://www.rust-lang.org/en-US/ is now 404 so tried to fix it, and could not resist to fix the spelling of GitHub, too.
Cheers.
> Fix few typos and 404 link in README.md

- src/core/initialize.rs
I use `rvm` so my `ruby` binary isn't at the hardcoded location. Therefore, certain tests fail.
This PR changes to just using the `ruby` name.
There is also a MacOS test which references a specific path but I don't use it so I can't verify if it'd be correct.
> Fix broken Linux tests

- ci/docker-tests.sh
- ci/ruby-programs/unicode_stack.rb
Not every method in the stack trace will be ASCII so add an explicit test to handle potential regressions.
> Add test to verify unicode support

- Cargo.toml
- appveyor.yml
- ci/ruby-programs/ruby_forks.rb
- src/main.rs
- src/ui/descendents.rs
Tracing subprocesses is not possible on Microsoft Windows, yet.
This change
* Implements `get_proc_children()` function for Windows, using
`NtGetNextProcess` function. `NtGetNextProcess` is an undocumented
routine of ntdll, but this approach is said to perform better than
Process32First/Process32Next.
* Enables `--subprocesses` option for Windows.
* Refactors ruby_forks testing script to use `Kernel#spawn` instead of
`#Kernel#fork`, because the latter isn't supported in Windows'
Ruby.
> [#189] Implement --subprocesses on Windows

- src/ui/flamegraph.rs
The `min_width` went from being minimum pixels to percent of the graph width sometime from 0.7 -> 0.9.  Currently, using the default of 0.1% seems reasonable.
It think it would be worthwhile to consider allowing this and other options to be set from the CLI. Optionally, I think supporting a config file might be worthwhile too.
Fixes https://github.com/rbspy/rbspy/issues/239
> Fix fidelity of flamegraph SVGs

- Cargo.lock
PR adding FreeBSD support misses the lock file update (#238).
This change basically updates Cargo.lock
> Update cargo lock file

- src/core/ruby_version.rs
- src/core/types.rs
- src/storage/v0.rs
This patch adds timestamps to the ndjson file format emitted by rbspy.
This is useful for tools that take time into account, including speedscope (https://github.com/rbspy/rbspy/pull/161), google [cloud profiler](https://cloud.google.com/profiler/) (for continuous profiling), and [flamescope](https://github.com/Netflix/flamescope).
A sample line:
```
{"trace":[{"name":"<c function>","relative_path":"unknown","absolute_path":null,"lineno":0},{"name":"<c function>","relative_path":"unknown","absolute_path":null,"lineno":0},{"name":"block (2 levels) in spawn_thread","relative_path":"/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/thread_pool.rb","absolute_path":"/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/thread_pool.rb", …
```
> Include sample timestamps in file format

- src/core/types.rs
- src/main.rs
- src/storage/mod.rs
- src/storage/v0.rs
- src/storage/v1.rs
- src/storage/v2.rs
This is another approach to addressing https://github.com/rbspy/rbspy/issues/162. Potentially it would be useful to have both.
By storing the sample frequency, it's possible to infer approximately how much time a function spent on the stack.
This change requires a bump in the format version, since there is now a "header" line after the `rbspy02\n` line.
Sample output:
```
rbspy02
{"sample_rate":100,"rbspy_version":"0.3.8","start_time":{"secs_since_epoch":1586161110,"nanos_since_epoch":410485101}}
{"trace":[{"name":"<c function>","relative_path":"unknown","absolute_path":null,"lineno":0},{"name":"handle_servers","relative_path":"/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/server.rb","absolute_path":"/opt/gitlab/embedded/lib/ruby/gems/2.6.0/gems/gitlab-p …
```
> add header line to storage format, storing sample rate

- src/ui/speedscope.rs
This patch adds weights to the speedscope profile as proposed by @jlfwong.
It drops the first sample by assigning a weight of 0 (since we have no delta to compare to) and then assigns weights by comparing the timestamp to the previous one.
I don't have much experience with rust, so if there's any hints on how to make some of this nicer, I'd love to get some pointers!
Closes #252.
> add timestamp weights to speedscope output format

- scripts/Dockerfile
- scripts/README.md
- scripts/bindgen.sh
This allows you to run a bindgen in a relatively self-contained environment. Some hackery was needed to get it working, and it doesn't generate exactly the same files that exist in the repo, at least not yet. This is quite possibly due to differing bindgen versions, and possibly other updates in rust packages.
I had to go with an older debian version because older rubies require an older version of bison (https://bugs.ruby-lang.org/issues/17106).
I've opened a separate MR for `2_7_2`, which we don't have support for yet: https://github.com/rbspy/rbspy/pull/271.
> add Dockerfile for use with bindgen.sh

- Cargo.lock
- Cargo.toml
- README.md
Changelog:
- add support for ruby 2.4.10 and 2.5.2 (#272)
- add support for ruby 2.7.2, (#271)
- add timestamp weights to speedscope output format (#253)
- say that rbspy isn't an on-CPU profiler
I also added documentation for the release process, as per https://github.com/rbspy/rbspy/pull/272#issuecomment-723440469.
> Prepare v0.3.11 release

- src/core/ruby_version.rs
it looks like on linux arm `libc::char` is `u8`, not `i8`, so I just replace `i8` with `libc::char` to make this code more portable.
To test it I used the following Dockerfile:
```Dockerfile
FROM alpine:3.12 as rust-builder
RUN apk update &&\
apk add git gcc g++ make build-base openssl-dev musl musl-dev \
rust cargo curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
RUN /root/.cargo/bin/rustup target add $(uname -m)-unknown-linux-musl
RUN wget https://github.com/libunwind/libunwind/releases/download/v1.3.1/libunwind-1.3.1.tar.gz
RUN tar -zxvf libunwind-1.3.1.tar.gz
RUN cd libunwind-1.3.1/ && ./configure --disable-minidebuginfo --enable-ptrace --disable-tests --disable-documentation && make && make install
COPY . /opt/rbspy
WORKDIR /opt/rbspy
ENV RUSTFLAGS="-C …
```
> Adds support for linux arm builds

- .github/workflows/publish-crate.yml
This aims to fix #277 
I don't know how to test this, so I'm just going to merge it, create a release, and see if it publishes a crate. I copied this from https://github.com/rillrate/rillrate-js/blob/ab5b83d1ea50d1673cbcbb8f5cf75ece7966f24c/.github/workflows/release-crates.yaml.
> Add GitHub action to publish to crates.io on release

- src/main.rs
This is my attempt to address https://github.com/rbspy/rbspy/pull/273#issuecomment-724801951.
`test_spawn_record_children_subprocesses` has been quite flaky, frequently reporting 3 processes instead of the expected 4. by increasing the sample rate from 10hz we can hopefully get enough samples to consistently see all processes.
🤞
> reduce sensitivity of flaky test

- ci/ruby-programs/ruby_forks.rb
- src/core/initialize.rs
- src/core/types.rs
- src/main.rs
(... hopefully.)
The `test_spawn_record_children_subprocesses` has been failing consistently for me locally (macOS 11.2.1, 2019 MBP). I noticed that the test process was returning an error immediately -- before ruby_forks.rb had exited, and maybe before it had even started -- which made me wonder whether there was a startup delay that we weren't accounting for. Indeed, it seems to take a few hundred milliseconds before we can get a handle on the process. If we wait for that handle before spawning the recorders, it works consistently for me.
After fixing that, I noticed an intermittent related issue where the trace sender channel was filling up. I think that's the reason for the timeouts we've seen in CI recently -- the sender channel fills up, which blocks some recorders from exiting, …
> Fix flaky subprocess test

- ci/ruby-programs/ruby_forks.rb
- src/core/types.rs
- src/main.rs
We've still been seeing subprocess test failures in CI, especially on Windows. This PR refactors the subprocess test to coordinate with ruby_forks.rb using the filesystem instead of depending on the ruby processes' startup speed. The last commit is an ugly workaround for process exit behavior that hopefully can be fixed (maybe by #295).
> Synchronous subprocess test

- src/core/ruby_version.rs
This is a workaround for the "early exit" bug. I was able to consistently repro this bug by running rbspy against rspec while it was running the test suite for a decent-sized Rails app. The proximate cause here is that we're trying to dereference a pointer to a memory address like `8`, which isn't valid (might be a length), and remoteprocess returns an error (code 60) that we map to `ProcessEnded` when we try to copy the memory. Maybe that error code covers more scenarios than process exit.
In my testing, we only seem to go down the RArray code path for strings like `<internal:gc>`. I suspect that those are encoded differently than normal strings. We have an implementation of ruby's `string2cstring` GDB macro in the C symbol resolution code that might be useful here -- it has two code …
> Gracefully handle invalid pointers to absolute path strings

- Cargo.toml
I asked @acj if he'd be willing to be rbspy's lead maintainer since he's already been doing the work of adding support for new Ruby versions, implementing new features, fixing bugs, and improving the CI for the last couple of months, and he agreed!
This change to Cargo.toml is just symbolic: I've already given him all the GitHub/Cargo permissions he needs.
I'm extremely excited to have someone who's actually using rbspy as the maintainer.
> Add @acj as an author to Cargo.toml

- CONTRIBUTORS.md
- README.md
The contributors list was incredibly out of date, so this replaces it with a new CONTRIBUTORS.md file with the goal of recognizing contributors who helped make rbspy possible but aren't in the commit log.
> Move contributors list to CONTRIBUTORS.md

- .github/workflows/ruby-bindings.yml
- scripts/bindgen.sh
It's currently a tedious manual process to generate bindings for new (or existing) ruby versions. The process is predictable, though, and I wondered if it could be fully automated. Happily, the answer is yes.
This PR adds a new GitHub Actions workflow that generates the bindings for (almost) all of our supported rubies from 1.9.3 through 3.0.1. The workflow currently needs to be triggered manually in the Actions tab. Assuming the builds succeed, it will gather the generated source files and create a new branch that contains any changes or additions. We could eventually have it open a PR if we wanted.
The bindgen script can still be run in isolation just as before, but I'm hoping that we won't need to do that very often.
If we ever need to generate separate bindings for each platform (like …
> Add workflow for generating ruby bindings

- ci/ruby-programs/recurse-sleep.rb
- src/main.rs
- src/ui/flamegraph.rs
Following suggestion #275, here is my first rust PR :tada: 
Ok so the idea is to be able to control the `min_width` [option from inferno](https://docs.rs/inferno/0.10.1/inferno/flamegraph/struct.Options.html#structfield.min_width) which is currently kept to the default of `0.1%`. It could be useful for people like me who run long profiling (and so have many sample so good precision) to be able to decrease this number to have more details in smaller flames.
So in this PR I tried to add a `flamegraph-precision` option, which is an integer (I couldn't manage to put a float in the `Record` struct), defined as:
```
> rbspy record --help
...
OPTIONS:
...
--flamegraph-precision <PRECISION>    Minimum flame width = 1/PRECISION % [default: 10]
```
So default value of 10 = 0.1%, setting 1 would …
> Add flamegraph precision option to control min_width

- src/main.rs
rbspy currently stops profiling when any one of the processes it's tracking exits. This creates a subtle race condition for the subprocess test, which has been very flaky on macOS and Windows, and also seems like undesirable behavior since subprocesses are expected to come and go in many applications. There may also be use cases where the root process is expected to exit before its subprocesses, but I think this change will cover the 99% case pretty well.
I realized this while experimenting with `--test-threads` for an unrelated issue. When I limited the threads to one or two (which is close to CI worker specs), the subprocess test consistently failed.
@jvns, when you have a moment could you please take a peek at this? I'm curious if there's a historical reason why we were exiting as soon …
> Fix subprocess exit bug

- Cargo.lock
- Cargo.toml
- src/core/initialize.rs
- src/main.rs
We don't currently pause the target process when calling `get_stack_frame`, which results in incorrect and misleading profiler output like we see in #315. The `remoteprocess` crate has support for pausing processes on each platform. The output seems much more accurate in my testing, so I'm going to enable it.
Using higher sampling frequencies will degrade performance of the target process while rbspy is running, but 1) this is already true, at least on some systems, because of higher CPU usage, and 2) it feels like a reasonable tradeoff for the sake of correctness. If we find that it's a problem, we could consider adding a flag to disable pausing.
Fixes #153. Fixes #315.
> Pause target process when retrieving stack frames

- Cargo.lock
- Cargo.toml
- src/core/types.rs
- src/ui/mod.rs
- src/ui/output.rs
- src/ui/perftools.profiles.rs
- src/ui/pprof.rs
This adds a new outputter to support the trace output format described here: https://github.com/google/pprof/tree/master/proto.  This is a format typically used to profile golang programs.  It can be used to upload traces to [Google Cloud Profiler](https://cloud.google.com/profiler), and [Speedscope also supports it](https://github.com/jlfwong/speedscope/wiki/Importing-from-pprof-(go)).
I've closely followed the approach used to add Speedscope support, so most of it should be fairly self-explanatory.
~In the first commit, I've also done some refactoring in `Recorder::record()` to expand the API a bit without changing functionality.  This was helpful in implementing an additional `Recorder` trait for another project I'm working on.  If this change is undesirable, the `pprof`-related code …
> Add pprof output format

- src/ui/pprof.rs
Although any arbitrary string can be used for `sample_type` units in pprof format, I've accidentally learned that the user experience in Google Cloud Profiler and Speedscope can be improved by specifying these units as "nanoseconds".  When using "ns" we see large numbers with a lot of commas everywhere, but by changing to "nanoseconds" we get automatically scaled display units like "ms" and "s".
Before and after (different samples):
> Enhance the user experience in pprof-consuming apps by adjusting units

- src/lib.rs
Any reason why these types are private? I'm integrating rbspy with https://github.com/pyroscope-io/pyroscope-rs and they could be useful. So far, I'm using StackTrace, but I think more types could be exposed.
> refactor: export StackTrace type

- examples/record.rs
- examples/snapshot.rs
- src/core/initialize.rs
- src/main.rs
- src/recorder/record.rs
- src/recorder/snapshot.rs
- src/sampler/mod.rs
Testing new versions of ruby before they're released is currently a bit of a pain. You need to mention the new version string(s) in a few places, run bindgen, and recompile. However, breaking changes to the ruby C types that rbspy cares about are fairly rare, and using the types from the previous ruby version usually works fine. This PR adds a `--force-version` flag that overrides the version detection that rbspy normally performs.
The flag might also be useful for anyone maintaining a custom ruby build that has a unique version string but is otherwise compatible with upstream ruby.
For example, I have ruby 3.1.1 installed on my computer, and today I wanted to check rbspy's compatibility with [3.2.0 preview 1](https://www.ruby-lang.org/en/news/2022/04/03/ruby-3-2-0-preview1-released/) …
> Add --force-version flag for testing with pre-release rubies

- src/ui/pprof.rs
Resolves #367. When sampling multiple processes, the order in which the samples arrive at the stats recorder is nondeterministic. That can result in awkward calculations where the previous sample seems to have arrived after the current one.
There are several options for handling this. We could drop the current sample, or calculate the elapsed time backwards (treat the previous time as the next one), or assume that the timestamps arrived at the same time, etc. This workaround uses the latter. That is, we assume that no time has elapsed between the "previous" sample and the one that we're currently processing.
@saunderst, WDYT?
> pprof: Tolerate stack frame timestamps arriving out of order

- Cargo.lock
- Cargo.toml
The dependency is optional for chrono and enabled by default for backward compatibility only.
See: https://rustsec.org/advisories/RUSTSEC-2020-0071
See: https://github.com/chronotope/chrono/blob/v0.4.23/CHANGELOG.md#0416
> sec: Remove vulnerable time-0.1.x chrono dependency
