rbspy/rbspy

Cargo.toml
src/dwarf.rs
src/lib.rs

This was originally #5 by @dirk. I rebased and made it build on Linux.

Add initial OS X support

---

Cargo.toml
License.md

License add

---

src/lib.rs

Previously I'd defined 2 versions of every function to support different Ruby versions. (even if the code was identical)
That was no good! This gets rid of the code duplication by reorganizing how the macros work. Then in `ruby_bindings_v2`, I can just say which version of each function I want.

Refactor macros for different Ruby version support to get rid of code duplication

---

src/lib.rs

This adds support for Ruby 1.9.x programs! After this commit, profiling system Ruby (Ruby 1.9.1) on Ubuntu 14.04 works, which is extremely exciting
Various exciting internal improvements in this commit which enabled this:
* When loading a symbol, do the address calculation as `map.range_start + symbol_addr - load_header.vaddr` instead of `map.range_start + symbol_addr`. The `load_header.vaddr` adjustment is very important, and was preventing the profiler from working on Ruby 1.9.x on my laptop!
* Compile a different version of `is_maybe_thread` for each Ruby version (using macros). This will let us to (theoretically!) work with any system Ruby version.
* restructure most of the `address_finder` to calculate a big `ProgramInfo` struct. The idea is that we make one big ProgramInfo struct up …

Support profiling Ruby 1.9.x programs

---

build.sh
docker/Dockerfile.arch2018
docker/Dockerfile.fedora
docker/Dockerfile.ubuntu1604
docker/Dockerfile.ubuntu1704

Test a LOT more ruby versions. Also add tests for Arch and Ubuntu 17.04.

Set up more extensive tests

---

Cargo.lock
Cargo.toml
ci/docker-tests.sh
src/bin/ruby-stacktrace.rs
src/lib.rs

This switches the previous command line arguments to simpler "snapshot" and "record" arguments!

Implement "snapshot" and "record" features from README

---

CODE_OF_CONDUCT.md
README.md

rewrite README to get closer to a release

Rewrite README

---

src/main.rs

- structured arguments
- us path types instead of strings
- some improved error handling

main: Various improvements

---

src/main.rs

Previously we were always sleeping for an integer number of milliseconds between sampler runs. This isn't very accurate -- if someone wants to sample (say) 172 times per second, we should sleep for 5.8 milliseconds, not 6 milliseconds.
This changes the `record` function to use `Duration::new(0, num_nanoseconds)` instead of `Duration::from_millis(num_millis)` so we can sleep more accurately.
cc @liaden

Specify sleep time in nanoseconds instead of ms

---

src/copy.rs

there's an issue (#64) where if some memory is incorrect, we can end up passing in an invalid length to `copy_address_raw` (length = some huge number), then allocating huge amounts of memory in `copy_address_raw` and the program crashes. This PR doesn't fix the underlying issue (why is the memory in an invalid state?), but it should avoid allocating huge amounts of memory and instead log an error and continue. The choice of 1MB is arbitrary.
In the future we should be more disciplined about logging more detailed output than this when there's an error (so it's possible to ask users for the debug output)

Return an error if we request more than 1Mb of memory in copy_address_raw

---

src/main.rs

@vasi's callgrind PR (#75) made the Ctrl+C handling way better, which means we can actually simplify it even more! There's no need anymore to handle Ctrl+C a different way in `record` depending on whether we're running a subcommand or not.

Simplify Ctrl+C handling

---

src/main.rs

Previously we were sampling 100 times per second by doing a sleep (1 billion nanoseconds / 100). This isn't totally accurate because of course *taking* a sample takes a nonzero amount of time.  This introduced a skew on my laptop of about 3%.
This fixes that by using a smarter strategy for sleeping -- instead of sleeping for X nanoseconds, instead we calculate the expected next sample time and sleep until that time.

Make sure we sample the correct number of times per second

---

src/main.rs

Fixes https://github.com/rbspy/rbspy/issues/82
#79 made sampling more accurate (yay!) but introduced an issue where rbspy would crash if it fell behind its expected sampling times (for example because someone is sampling at too high of a rate). This changes it so that rbspy will warn that results may be inaccurate and that it's dropping a sample, but it won't crash.

Don't crash if we fall behind our expected sample time

---

src/initialize.rs

from @parkr's great suggestion on https://github.com/rbspy/rbspy/issues/80 -- previously we weren't ever retrying turning a PID into a task if it failed. This changes it so that we retry.
I forgot about this before because on Linux `.try_into_process_handle()` always succeeds, but on Mac it can fail and have races, so it makes sense to retry it.

Retry turning PID into process handle if it fails

---

src/callgrind.rs

Also new rustfmt.
Please read these over and validate that the comments are actually helpful. I'm happy to make changes to improve it!

Add comments/docs for callgrind module

---

src/main.rs

Fixes #112 (which asked for this feature)
cc @segiddins

Print out amount of time since profiling started

---

src/core/address_finder.rs
src/core/copy.rs

People get tripped up by this pretty frequently, so let's make the error message more helpful :)

Explain how to add SYS_PTRACE capability to Docker in error message

---

src/main.rs

Suggest reporting a GitHub issue if there are an abnormally high number of errors

---

Cargo.lock
Cargo.toml
src/core/address_finder.rs
src/core/initialize.rs
src/core/ruby_version.rs
src/main.rs
src/storage/mod.rs
src/storage/v0.rs
src/storage/v1.rs
src/ui/callgrind.rs
src/ui/descendents.rs
src/ui/flamegraph.rs
src/ui/output.rs
src/ui/speedscope.rs
src/ui/summary.rs

* switch to Rust 2018
* clippy suggestions
* dependency update

Code updates

---

Cargo.lock
Cargo.toml

Downgrade nix

---

Cargo.toml

@jvns Is there anything else needed other than this and creating a new release for it to create the new release artifacts?

Bump version for new release

---

src/core/address_finder.rs

Adds macOS M1 support, fixes #279, there's more context in the issue.

macOS M1 support - get_dyld_info works better than get_process_maps

---

.github/workflows/ci.yml

Also try running mac tests as root

Add linux cross compile code

---

.github/workflows/ci.yml

Going to push a billion changes to this branch

Try out using github actions for CI

---

src/core/address_finder.rs
src/core/initialize.rs
src/core/ruby_version.rs
src/core/types.rs
src/main.rs
src/storage/mod.rs
src/storage/v0.rs
src/storage/v1.rs
src/storage/v2.rs
src/ui/flamegraph.rs
src/ui/speedscope.rs
src/ui/summary.rs

Building on #235. Fixes #234, closes #235.

Fix build warnings

---

.gitignore

Hi @acj add 'examples' generated file into .gitignore

.gitignore: flamegraph.svg, rbspy-out.svg, rbspy-raw.txt
